// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsICJGQnljD_jqMikBKMWsMRF--_VgVG8',
    appId: '1:683332775487:web:82a63749eb156de33ed28a',
    messagingSenderId: '683332775487',
    projectId: 'notes-app-f8a29',
    authDomain: 'notes-app-f8a29.firebaseapp.com',
    storageBucket: 'notes-app-f8a29.appspot.com',
    measurementId: 'G-986RK4TSSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA43PhZfZnznU_uguteeXipiJ5LltN8K7M',
    appId: '1:683332775487:android:daafa3d95036f4483ed28a',
    messagingSenderId: '683332775487',
    projectId: 'notes-app-f8a29',
    storageBucket: 'notes-app-f8a29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy460gzNUbF43UNm8U4lnWfWKRW4N3KVs',
    appId: '1:683332775487:ios:41cca9f4d1715f003ed28a',
    messagingSenderId: '683332775487',
    projectId: 'notes-app-f8a29',
    storageBucket: 'notes-app-f8a29.appspot.com',
    iosClientId: '683332775487-tt386gg29sn7odf3nbj8a3r3hu0atrrq.apps.googleusercontent.com',
    iosBundleId: 'com.samuelgadiel.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy460gzNUbF43UNm8U4lnWfWKRW4N3KVs',
    appId: '1:683332775487:ios:41cca9f4d1715f003ed28a',
    messagingSenderId: '683332775487',
    projectId: 'notes-app-f8a29',
    storageBucket: 'notes-app-f8a29.appspot.com',
    iosClientId: '683332775487-tt386gg29sn7odf3nbj8a3r3hu0atrrq.apps.googleusercontent.com',
    iosBundleId: 'com.samuelgadiel.notes',
  );
}
